### PR TITLE
Default 15 SecondsPerBlock included to neo-cli

### PR DESCRIPTION
**Pull request by vncoelho**

### CODE REVIEW

**Comment by metachris** [comment]
This PR makes no sense, it's already 15 seconds by default, and this setting has no effect even if it's any other number.

**Comment by vncoelho** [comment]
Hey, @metachris, at the end, it is now making some different.
Perhaps, after the last commit/improvements on Neo library blockchain and neo-cli itself.

Please, accept this pull request.

**Comment by vncoelho** [comment]
https://cdn.discordapp.com/attachments/405021672039776268/431421007048474624/unknown.png

**Comment by metachris** [comment]
In general, I'd love to have adjustable block times. But I've tested it too and the settings doesn't seem to make a difference.

Also, isn't 15 seconds the default? What would this PR improve?

Can you please try setting it to both 60 seconds and to 5 seconds to see if it actually makes a difference? Please include screenshots.

**Comment by vncoelho** [comment]
Five seconds I already tried, perhaps, the one I sent you on Discord.
The screenshot was also already sent above (https://cdn.discordapp.com/attachments/405021672039776268/431421007048474624/unknown.png). 
It is currently not able to always match this value, however, some modifications obviously occur in the client communications and syncing protocols.
Anyway, do not expect an incredible modification, there are other bottlenecks...aehuaheauhuea 
Furthermore, just to be clear for those that may read this, it still does not increase tx/s (it has potential, thanks to several improvements that are going on on Neo Blockchain Library and Neo-Cli itself), but other variables still should be verified. 
Anyway, @metachris, soon of later it will work.
Some people will like to play with this parameter.  As default, the repository should have 15 seconds.

I think that the neo-cli here some follow the same template as the original project, it helps everyone for following all modifications. In the original it is also like this nowadays.

With 60 seconds I did not check yet. My internet is constrained here, I am just flying from Sri Lanka to Brazil.
I will soon check it out.
If you want to try it by yourself in an easy manner, consider https://github.com/NeoResearch/neo-integration-tests, the original templates was done by @AshRolls.
Other files from original Neo Blockchain and Neo-Cli can also easily be modified.

If this PR is accepted, consider accepting #43, because it may make the building process a little faster, avoiding git clone after changes on the protocol.

**Comment by metachris** [comment]
If you can change the settings to 60 seconds and 5 seconds and provide screenshots to prove it works, this PR could be merged. 

I couldn't get it to work, perhaps I did something wrong. 

Please try it out and post screenshots, then we can continue the PR.

PS: #43 is already merged

**Comment by vncoelho** [comment]
@metachris, sorry to say that, but I do not like this way you are talking.

First of all, this PR has nothing to do with speed up or increasing blocks per second. It is just about adequating the template of this repository with neo-cli.
I use and frequently pull this project in connection with various other ideas/frameworks, thus, in order to avoid adding this line all the time, I am suggesting you to follow neo-cli template. 

These experiments that you "requested" are interest and we were already conducting them. However, they are not the main point of this PR.
We will keep doing them and soon we will probably have more insights. 

Maybe, you/we could open an issue on neo-cli or neo project and we could continue this discussion there.
It will be better and more profitable to have more people engaged. Furthermore, here it sounds like you ordering something, it is not nice at all.

Sorry for mentioning it, but, on the other hand, really thank you for everything and tips that you do.

Finally, there is no sense to keep this discussion here. In this sense, I just suggest the acceptance of this little adjustment in accordance with state-of-the-art neo-cli project.
Otherwise, just leave it closed.

ps: thanks for #43

**Comment by AshRolls** [comment]
This change does more closely align the privatenet setup with the expected json format of neo / neo-cli.

If there is a problem where changing the value is not actually altering up the block generation time then it should be logged as a new issue at the main repo.

**Comment by metachris** [comment]
@vncoelho - sorry, didn't want to offend you with my tone. Was just playing around with this setting and it seemed to not have any effect, thereby I didn't want to add it because it might give people the wrong impression that it actually would work. But the argument from @AshRolls is fine too that it more closely aligns with the neo-cli json.

**Comment by DaveOnBlocks** [comment]
I setup a local network using Slipo's neo-scan-docker container (https://github.com/slipo/neo-scan-docker). I killed all the nodes and then changed the protocol.json to be: 
```
{
    "ProtocolConfiguration": {
        "Magic": 56753,
        "AddressVersion": 23,
        "SecondsPerBlock": 60,
        "StandbyValidators": [
            "02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2",
            "02103a7f7dd016558597f7960d27c516a4394fd968b9e65155eb4b013e4040406e",
            "03d90c07df63e690ce77912e10ab51acc944b66860237b608c4f8f8309e71ee699",
            "02a7bc55fe8684e0119768d104ba30795bdcc86619e864add26156723ed185cd62"
        ],
        "SeedList": [
            "127.0.0.1:20333",
            "127.0.0.1:20334",
            "127.0.0.1:20335",
            "127.0.0.1:20336"
        ],
        "SystemFee": {
            "EnrollmentTransaction": 1000,
            "IssueTransaction": 500,
            "PublishTransaction": 500,
            "RegisterTransaction": 10000
        }
    }
}
```

The neo-scan showed 60 second blocks. When I changed it to 5 second blocks, I got around 8 second blocks. 

5 Second Blocks:
5-seconds

60 Second Blocks:
60-seconds


So for me it seems to be working but I would like other people to confirm it as well to make sure I am not doing something unique!

**Comment by vncoelho** [comment]
@DaveOnBlocks , that is true, Dave.

image

Now, the print with the new neo-scan version. :dagger:

**Pull request merged**
