### PR TITLE
neo-cli 2.7.5

### PR DESCRIPTION
**Pull request by metachris**
Do not merge yet

### CODE REVIEW

**Comment by ixje** [comment]
I believe we can close this. The current `Latest` tag is on `2.7.6` and should be updated to 2.9.0 as per https://github.com/CityOfZion/neo-privatenet-docker/issues/55

**Comment by metachris** [comment]
Hm, the master branch is on 2.7.4

**Comment by ixje** [comment]
🤔 
that's odd, on Dockerhub it's `2.7.6` [link](https://hub.docker.com/r/cityofzion/neo-privatenet/tags/) and that's definitely running 2.7.6

```
Eriks-Air:neo-python-core erik$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
cityofzion/neo-privatenet   latest              aa9992e81b4f        3 months ago        2.79GB
cityofzion/neo-privatenet   <none>              c6562de84ae0        6 months ago        2.83GB
Eriks-Air:neo-python-core erik$ docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                                        NAMES
16c3a4325b1b        cityofzion/neo-privatenet   "/bin/bash /opt/run.…"   2 days ago          Up 2 days           0.0.0.0:20333-20336->20333-20336/tcp, 0.0.0.0:30333-30336->30333-30336/tcp   neo-privatenet
Eriks-Air:neo-python-core erik$ nc 127.0.0.1 20333
��version'�ܾ�f��[mO��,
                     /NEO:2.7.6/�,
```

**Comment by metachris** [comment]
Yeah, perhaps I just fixed the code locally and produced an image. I'll see if I can find a little time tomorrow to fix the current error.

**Pull request closed without merging**
