### PR TITLE
Update wait_for_tx function

### PR DESCRIPTION
**Pull request by vncoelho**
Current Neo-python accepts tx.Hash for getting a transaction.

Previous convertion was not being supported anymore

### CODE REVIEW

**Comment by metachris** [comment]
I'll take a closer look at this once we have the fix for the current issues in neo-python.

**Comment by vncoelho** [comment]
It works, I tested here.
There is not reason to not accept. O.o

**Comment by vncoelho** [comment]
Even with older version of Neo-Python it does not have problems in the way it is exemplified in this pull request.

**Comment by metachris** [comment]
The tests are failing, which is a reason to wait and investigate.

**Comment by vncoelho** [comment]
I see.
Actually, I do not know how this test you are mentioning works. Sorry.

Anyway, I will also double check it.

**Comment by vncoelho** [comment]
I got, I saw the result now:

File "/opt/neo-python/neo/SmartContract/ContractParameterContext.py", line 53, in <listcomp>
    jsn['parameters'] = [p.ToJson() for p in self.ContractParameters]
  File "/opt/neo-python/neo/SmartContract/ContractParameterContext.py", line 29, in ToJson
    jsn['type'] = ToName(self.Type)
  File "/opt/neo-python/neo/SmartContract/ContractParameterType.py", line 64, in ToName
    val = int(item[1])
builtins.TypeError: int() argument must be a string, a bytes-like object or a number, not 'ContractParameterType'


It is a great way of checking integrity of the repository. Congratulations. Very well organized.

**Comment by metachris** [comment]
A solution at neo-python is on the way. Just wait a little, I'll message you on Discord once it is through.

**Comment by metachris** [comment]
I've looked at these changes and I'm not sure what you are trying to achieve. This has nothing to do with neo-python. You just changed the method signature for `wait_for_tx` to use the hash instead of the transaction itself, but using the transaction is much more useful than just the hash.

So without a very good reason I don't want to merge this RP since it seems to actually be reducing functionality without improving anything.

**Comment by vncoelho** [comment]
Actually, I tried to use the TXID, as you were doing.
But these previous functions are not implemented in neo-python anymore.
I do not know why, but tx.Hash.ToScrypt() lead to problems here.

We could use UInt256:
"txid = UInt256.ParseString(get_arg(args)) 
tx, height = Blockchain.Default().GetTransaction(txid)"
Changing  get_arg(args) -> tx.Hash.ToBytes()

However, since Neo-Python was not compiling due to other problems. I solved it locally using the Hash.
It was useful here in my solution.

I probably did some confusions and mistakes due to other errors on Python.
I need to check again...

**Pull request closed without merging**
