### PR TITLE
Upgraded to NEP-6 JSON wallets (using neo-cli 2.5.2)

### PR DESCRIPTION
**Pull request by metachris**
Do not merge this yet! `neo-cli` is still not finding consensus. This PR is used to track WIP with @AshRolls to get the consensus contract inside.

### CODE REVIEW

**Comment by AshRolls** [comment]
We should probably delete the old .db3 files as well

**Comment by metachris** [comment]
@AshRolls merge this? seems to work 👍

**Comment by metachris** [comment]
Don't merge yet. Need to double-check RPC, might not work

**Comment by metachris** [comment]
Confirmed that RPC still works 👍  Could merge this.

**Pull request merged**
