### PR TITLE
Install dotnet runtime instead of full sdk

### PR DESCRIPTION
**Pull request by nunojusto**
Solving issue https://github.com/CityOfZion/neo-privatenet-docker/issues/53

- neo-cli does not need full dotnet sdk to run and the dotnet runtime is a lot smaller.
- Also, I've used as a base the official microsoft/dotnet image ubuntu bionic.

Advantages:
Size of the docker image decreased 55% from 2.79GB to 1.26GB
image

### CODE REVIEW

**Comment by nunojusto** [comment]
no-cli runs ok, but it's failing the travis tests.
So something is wrong.
Investigating...

**Comment by nunojusto** [comment]
It seems the wallet has some problems. Because it's failing also without this PR. (see https://travis-ci.org/nunojusto/neo-privatenet-docker/builds/434392605?utm_source=github_status&utm_medium=notification)
So it might be other thing and not this PR.

@metachris Does this wallet needs to be converted for the new format?

**Comment by nunojusto** [comment]
is this the error?

```root@a88af95c3ea3:/neo-python# python3.6 /neo-python/claim_neo_and_gas_fixedwallet.py
Privatenet useragent '/NEO:2.7.6/', nonce: 155617858
Traceback (most recent call last):
  File "/neo-python/claim_neo_and_gas_fixedwallet.py", line 286, in <module>
    settings.setup_privnet()
  File "/neo-python/neo/Settings.py", line 232, in setup_privnet
    self.check_privatenet()
  File "/neo-python/neo/Settings.py", line 325, in check_privatenet
    "Consider deleting the Chain directory with 'rm -rf %s*'." % self.chain_leveldb_path
neo.Settings.PrivnetConnectionError: Chain database in Chains/privnet is for a different private network than the current container. Consider deleting the Chain directory with 'rm -rf /root/.neopython/Chains/privnet*'.```

**Comment by ixje** [comment]
I'm seeing this in the build log
```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/neo-python/claim_neo_and_gas_fixedwallet.py", line 219, in run
    claim_tx, relayed = ClaimGas(self.wallet, require_password=False)
builtins.TypeError: 'bool' object is not iterable
```

Some paths in `ClaimGas` don't return a tuple ([example](https://github.com/CityOfZion/neo-python/blob/773e57e72b24a00f6d6d0f9b6fe701e3bb0e7d31/neo/Prompt/Commands/Wallet.py#L149)) and this needs to be fixed on the neo-python side. I can look into that tonight when i get home

**Comment by metachris** [comment]
Testing right now...

**Comment by metachris** [comment]
Nice, works and now the image has half the size, with 1.26GB 👍 Thanks

**Pull request merged**
